#!/bin/zsh
autoload -U promptinit
promptinit
prompt adam1 232 214 208

# for vcs
setopt prompt_subst
autoload -Uz vcs_info
zstyle ':vcs_info:*' actionformats \
      '%F{5}(%f%s%F{5})%F{3}-%F{5}[%F{2}%b%F{3}|%F{1}%a%F{5}]%f '
zstyle ':vcs_info:*' formats       \
      '%F{5}(%f%s%F{5})%F{3}-%F{5}[%F{2}%b%F{5}]%f '
zstyle ':vcs_info:(sv[nk]|bzr):*' branchformat '%b%F{1}:%F{3}%r'

zstyle ':vcs_info:*' enable git cvs svn hg
# or use pre_cmd, see man zshcontrib
vcs_info_wrapper() {
  vcs_info
  if [ -n "$vcs_info_msg_0_" ]; then
    echo "%{$fg[grey]%}${vcs_info_msg_0_}%{$reset_color%}${del}"
  fi
}

kube_context() {
  kubectl config current-context 2>/dev/null| awk '
    {
      n=split($1,arr,"-")
      if(n == 1) {
        print $1
        next
      }
      if(n == 2) {
        print arr[n-1]"-"arr[n]
      } else {
        print arr[n-2]"-"arr[n-1]"-"arr[n]
      }
    }'
}

get_namespace() {
  local ns
  ns=$(kubectl config view --minify=true -o jsonpath="{..context.namespace}" 2>/dev/null)
  : "${ns:=default}"
  echo "$ns"
}

RPROMPT=$'$(vcs_info_wrapper) <%F{5}$(kube_context)%f:%F{4}$(get_namespace)%f> %F{3}$(date +%H:%M:%S)'
export RPROMPT
setopt transient_rprompt

